[package]
name = "repl_lib"
version = "0.2.2"
edition = "2024"
description = "Library for creating REPL interpreters."
license = "MIT"
repository = "https://github.com/sebastian-j-ibanez/repl_suite"

[dependencies]
term_manager = "0.1.3"
