[package]
name = "repl_demo"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/sebastian-j-ibanez/repl_suite"

[dependencies]
libc = "0.2.175"
# repl_lib = "0.1.2"
repl_lib = { path = "../repl_lib" }
